### ISSUE TITLE
Strange cursor behaviour caused by lazyredraw

### ISSUE THREAD

**Issue by bwot** [bwot/init.neovim#2]
Cursor does strange jumps and aren't where you'd expect it to be sometimes... Fixed by setting `set nolazyredraw` which brings back lag (the reason lazyredraw is set to begin with). Strange thing is that I've always used lazyredraw before. So something must have changed between my old init.vim and init.neovim.

Will investigate...

**Comment by bwot** [comment]
Can't figure out what caused this. Will put this on hold and just disable `lazyredraw` for now.

**Comment by bwot** [comment]
Lazyredraw has only been trouble to me the last couple of days. No idea how anything changed to make it behave different, but I'll probably remove it completely soon if nothing changes.

**Comment by KmBKeef** [comment]
What kind of lag?
